[package]
name = "simple-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
glam = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_decimal_macros = "1.36.0"
rust_decimal = "1.36.0"
