[package]
name = "physics_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
bincode = "1.3"
glam = { version = "0.24", features = ["serde"] }
image = "0.25.5"

[profile.release]
debug = true
